services:
  streamlit-app:
    build: .
    ports:
      - 8501:8501
    volumes:
      - ~/.cache/huggingface/hub:/home/user/.cache/huggingface/hub:rw
    environment:
      - PYTHONUNBUFFERED=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  postgres:
    image: ankane/pgvector:v0.5.0
    volumes:
      - psychology_qa_pgvector:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
  psychology_qa_pgvector:
