services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EMBEDDING_MODEL: $EMBEDDING_MODEL
        SENTENCE_TRANSFORMERS_HOME: $SENTENCE_TRANSFORMERS_HOME
    ports:
      - 8501:8501
    volumes:
      - ./psychology_qa:/home/user/psychology_qa
      - ~/.cache:/home/user/.cache:rw
    env_file:
      - .app.env
      - .postgres.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  postgres:
    image: ankane/pgvector:v0.5.0
    ports:
      - 5432:5432
    volumes:
      - psychology_qa_pgvector:/var/lib/postgresql/data:rw
    env_file:
      - .postgres.env

volumes:
  psychology_qa_pgvector:
