services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
      - ./psychology_qa:/root/psychology_qa
    #   - ~/.cache:/root/.cache:rw
    env_file:
      - .app.env
      - .postgres.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  postgres:
    image: ankane/pgvector:v0.5.0
    ports:
      - 5432:5432
    volumes:
      - psychology_qa_pgvector:/var/lib/postgresql/data:rw
    env_file:
      - .postgres.env

volumes:
  psychology_qa_pgvector:
