[[pages]]
path = "app.py"
name = "Psychology Q&A"
icon = ":brain:"

[[pages]]
path = "pages/upload_book.py"
name = "Upload a book"
icon = ":book:"

[[pages]]
path = "pages/upload_audio.py"
name = "Upload an audiobook"
icon = ":headphones:"
