name: Sync to Hugging Face Space
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hugging-face:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hugging face
        run: git push --force "https://$HF_USERNAME:$HF_TOKEN@$HF_SPACE" main
        env:
          HF_USERNAME: ${{ vars.HUGGING_FACE_USERNAME }}
          HF_SPACE: ${{ vars.HUGGING_FACE_SPACE }}
          HF_TOKEN: ${{ secrets.HUGGING_FACE_SYNC_TOKEN }}
