[[pages]]
path = "psychology_qa/app.py"
name = "Psychology Q&A"
icon = ":brain:"

[[pages]]
path = "psychology_qa/pages/library.py"
name = "Library"
icon = ":card_file_box:"

[[pages]]
path = "psychology_qa/pages/upload_book.py"
name = "Upload a book"
icon = ":book:"
